In [142]:
#from cvxopt import matrix, solvers
import pandas as pd
import numpy as np

In [143]:
data = pd.read_csv("Cov_M - Sheet2.csv") 
data1= pd.DataFrame(data)

In [144]:
x1=np.array(data1)

In [145]:
x=np.matrix.transpose(x1)

In [146]:
sigma=np.cov(x)

In [147]:
sigma

array([[ 7.02506827e-04,  2.61031508e-04,  2.23808650e-04,
         5.15980301e-05,  1.41585950e-04,  2.50172398e-04,
         8.67237941e-05,  1.41231993e-04,  2.55828448e-04,
         2.73211819e-04,  2.03214102e-04,  1.63355662e-04,
         1.32579887e-04,  1.95314057e-04,  1.02792325e-04,
         3.85985241e-05,  1.62422963e-04,  1.22779159e-04,
         1.39574283e-04,  3.44350646e-04],
       [ 2.61031508e-04,  3.41383883e-02,  2.43984113e-04,
        -2.32906979e-05,  2.88431699e-04,  2.91214055e-04,
         5.05647565e-05,  2.64479592e-04,  5.08343811e-04,
         5.80037341e-04,  4.40748518e-04,  4.80241967e-04,
         1.36902212e-04,  2.74852427e-04,  1.87051262e-04,
         5.44453803e-05,  2.04254544e-04,  3.54184875e-05,
         2.00756724e-04,  4.92481981e-04],
       [ 2.23808650e-04,  2.43984113e-04,  6.08450349e-04,
         1.20118585e-05,  1.41976309e-04,  1.78230110e-04,
         8.24326592e-05,  9.10221931e-05,  2.03632128e-04,
         2.33222503e-04,  1.6

In [148]:
sigma.shape

(20, 20)

In [149]:
sigmaT=np.matrix.transpose(sigma)
e= np.array([1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1])
eT=np.matrix.transpose(e)

In [150]:
w= sigmaT.dot(e)/(eT.dot(sigmaT.dot(e)))

In [151]:
w

array([0.04086046, 0.40024895, 0.03575539, 0.00644194, 0.02789791,
       0.05283024, 0.01799789, 0.02065771, 0.04712466, 0.04844704,
       0.03855982, 0.03574591, 0.0190146 , 0.03691775, 0.01780932,
       0.0058966 , 0.03296549, 0.02656232, 0.02440972, 0.06385627])

In [63]:
sum(w)

0.9999999999999998

In [64]:
#R will be given in the question for QP2

In [65]:
#how to find determinant 
b = np.array([[6,1,1], [4, -2, 5], [2,8,7]]) 
print b 
print np.linalg.det(b) 
print 6*(-2*7 - 5*8) - 1*(4*7 - 5*2) + 1*(4*8 - -2*2)

SyntaxError: Missing parentheses in call to 'print'. Did you mean print(b)? (<ipython-input-65-2e2ace5cbd7b>, line 3)

In [69]:
var_risk= (np.matrix.transpose(w).dot(sigma)).dot(w)

In [70]:
print(var_risk)

0.0057077143844649885


In [78]:
mew= np.array([0,-0.002630915533,-0.01258532649,-0.002020370918,-0.0005127697071,-0.001115248738,-0.006417886705,0.0004785751245,0.0009166778742,-0.00174750214,-0.001846967121,-0.002311161556,-0.002516427038,0.0006786801971,-0.001211335098,0.0008657222425,0.0003396692347,-0.001336734099,-0.001099446173,-0.001172031464])

In [106]:
#mew= np.array([-0.002630915533,-0.01258532649,-0.002020370918,-0.0005127697071,-0.001115248738,-0.006417886705,0.0004785751245,0.0009166778742,-0.00174750214,-0.001846967121,-0.002311161556,-0.002516427038,0.0006786801971,-0.001211335098,0.0008657222425,0.0003396692347,-0.001336734099,-0.001099446173,-0.001172031464])
e= np.array([1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1])
R=0.02
omg=sigma
#omgI=sigma
omgI = np.linalg.inv(omg) 

In [107]:
#finding v1 and v2

a1=((mew.T).dot(omgI)).dot(mew)
a2=((e.T).dot(omgI)).dot(mew)
a3=((mew.T).dot(omgI)).dot(e)
a4=((e.T).dot(omgI)).dot(e)

v11 = np.linalg.det(np.array([[a1,(2*R)], [a2, 2]]))
v12= np.linalg.det(np.array([[a1,a3], [a2, a4]]))
v21 = np.linalg.det(np.array([[(2*R),a3], [2, a4]]))
v22= np.linalg.det(np.array([[a1,a3], [a2, a4]]))

v1=v11/v12
v2=v21/v22

In [108]:
w2= 0.5*v1*(omgI.dot(e))+ 0.5*v2*(omgI.dot(e))

In [111]:
var_risk

31.702072368522657

In [112]:
w2

array([-2.70906092e+01, -9.28640118e-01,  1.01488508e+00,  8.18313555e+01,
        2.80484934e+01, -2.91791225e-01,  7.75647121e+01,  5.65864416e+01,
       -2.13073533e+01,  4.92800146e+00,  1.15696747e+01,  2.77928269e+01,
        1.08972817e+02, -3.13143180e-01,  8.78660533e+01,  2.97248860e+02,
        9.37405336e+00,  1.65388200e+01,  6.00956871e+01, -3.73966814e+01])

In [135]:
mew= np.array([0,-0.002630915533,-0.01258532649,-0.002020370918,-0.0005127697071,-0.001115248738,-0.006417886705,0.0004785751245,0.0009166778742,-0.00174750214,-0.001846967121,-0.002311161556,-0.002516427038,0.0006786801971,-0.001211335098,0.0008657222425,0.0003396692347,-0.001336734099,-0.001099446173,-0.001172031464])

In [136]:
np.average(mew)

-0.0017622399053550003

In [140]:
sig1= 
aa=(-0.0017622399053550003-0.0575)/sig1

In [141]:
sig1

array([[ 1.17288938e-06,  4.18170454e-05,  2.86127709e-07,
         2.14124848e-09,  1.10195427e-07,  6.98239766e-07,
         2.80919247e-08,  6.02694829e-08,  5.68126752e-07,
         6.41259734e-07,  3.02150890e-07,  2.08731006e-07,
         4.79349004e-08,  2.66197537e-07,  3.26028269e-08,
         1.34206422e-09,  1.76508839e-07,  8.66277050e-08,
         8.31631497e-08,  1.40413229e-06],
       [ 4.35812256e-07,  5.46894335e-03,  3.11920989e-07,
        -9.66532470e-10,  2.24484522e-07,  8.12788440e-07,
         1.63791419e-08,  1.12864287e-07,  1.12889603e-06,
         1.36141471e-06,  6.55331276e-07,  6.13638901e-07,
         4.94976581e-08,  3.74602015e-07,  5.93273854e-08,
         1.89305676e-09,  2.21968199e-07,  2.49897646e-08,
         1.19617749e-07,  2.00815611e-06],
       [ 3.73665820e-07,  3.90860659e-05,  7.77872100e-07,
         4.98475888e-10,  1.10499241e-07,  4.97446365e-07,
         2.67019227e-08,  3.88429022e-08,  4.52212647e-07,
         5.47400185e-07,  2.4